### ISSUE TITLE
Just use Browsers proxy settings instead of own GUI?

### ISSUE THREAD

**Issue by knobhead** [pedrocr/proxyswitcheroo#1]
Hi, thanks for your webextension! Basically it's just what I need: An on/off switch for Firefox.

But why does this extension bring its own, insufficient UI? Couldn't the toolbar button just toggle between "No Proxy" and the previously selected proxy settings in Firefox' preferences dialogue? 

Might make the extension even smaller!

**Comment by pedrocr** [comment]
I thought of doing just that initially but the API I found was the proxy one that needs to be done like this. Maybe there's a preference API that can be used instead but I haven't found it.

**Comment by pedrocr** [comment]
It is indeed not allowed:

https://wiki.mozilla.org/WebExtensions/FAQ#Does_the_WebExtensions_API_provide_access_to_preferences.3F

If you're missing preferences for other stuff just open an issue with that.

**Comment by pedrocr** [comment]
This can be fixed if this ever gets implemented:

https://bugzilla.mozilla.org/show_bug.cgi?id=1412790

So leaving open as that would indeed be the ideal way to do this.

**Comment by lightdot** [comment]
A nice, clean add-on! Thanks for providing this.

Looking at the implementation I also noticed that the browserSettings.proxyConfig API now exists in Firefox 59, so just a heads up in case you haven't noticed.

**Comment by pedrocr** [comment]
I've noticed yes, thanks and am planning on using it. The only downside is that, if I understood it correctly, the permission you'll have to accept is more like "change any firefox setting" and not "change the proxy settings" which would be the ideal.

**Comment by pedrocr** [comment]
As it turns out it doesn't seem extra permissions are needed.

**Comment by pedrocr** [comment]
Version 1.0 is now on the extension store with this new way of working. I called it 1.0 because now it does everything I wanted. The permissions are still very small and yet all the possible proxy settings firefox supports can be set by just using the normal config.

**Comment by knobhead** [comment]
Great  :heart_eyes_cat:  thanks a lot for your work! :+1:

However, I didn't manage to get it to work properly on FF 63.0.3 Win7 64bit. When I set it to "Use Manual Proxy Settings" in addon settings, the FF proxy settings dialogue empties all text fields and I can't enter new values and I have to click "Disable this extension now" to be able to enter proxy settings again.

Will try on Linux later. Let me know if I can give any more helpful debug information.

regards

**Comment by pedrocr** [comment]
The UI is perhaps a little confusing because of the way extensions work. You need to have the extension turned off (with the globe in grey) to be able to edit the settings. Then what the extension does is toggle between whatever setting you left it was (none, system, etc) to the setting you set in the config (usually manual).

**Comment by iamphpgo** [comment]
I also have the same problems and I do not know why this has been developed, it was simpler before.

**Comment by pedrocr** [comment]
@iamphpgo before the available settings in the extension didn't cover some use cases and so there were bug reports like this one. When the globe is grey you can't edit the proxy settings in the firefox preferences?

**Comment by pedrocr** [comment]
@knobhead @iamphpgo please confirm if what I described fixes things. The UX becomes confusing because of the settings block when the extension is in the ON state. I've filed a bug with Firefox to see if I can get API to fix this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1512545
