### ISSUE TITLE
source ProxySwitcheroo 0.4

### ISSUE THREAD

**Issue by iamphpgo** [pedrocr/proxyswitcheroo#2]
hi 
Is the source ProxySwitcheroo 0.4  free and under license GPL-3.0?

Is registered in about:addons firefox last updated july 14,2018 but registered in github lasted commit  on Nov 27, 2017.

thank you

**Comment by pedrocr** [comment]
License is indeed GPL3. The last update in the firefox registry is on the same date as the last commit:

https://addons.mozilla.org/en-US/firefox/addon/proxyswitcheroo/?src=search

That's Nov 27, there hasn't been any update since, it still does all I need it to do.
